services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    